-- ============================================================
-- SEED: Sistema de Recaudo Electrónico para Transporte Urbano
-- Estructura de 4 niveles PMBOK (50 actividades, 61 dependencias)
-- ============================================================

BEGIN TRANSACTION;

-- 1. Proyecto
INSERT INTO proyecto (id, nombre, descripcion, fecha_inicio, creado_en, actualizado_en) VALUES (1, 'Sistema de Recaudo Electrónico para Transporte Urbano', 'Implementación integral de sistema de recaudo con validadores IoT a bordo, motor transaccional offline-first y plataforma centralizada de gestión.', '2026-11-23', datetime('now'), datetime('now'));

-- 2. Nodos EDT (Raíz, Fases, Paquetes de Trabajo y Actividades)
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (1, 1, NULL, '1', 'Sistema de Recaudo Electrónico para Transporte Urbano', '', 0, 0);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (2, 1, 1, '1.1', 'Gestión del Proyecto', '', 0, 1);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (3, 1, 2, '1.1.1', 'Acta de constitución y alcance del proyecto', '', 0, 2);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (4, 1, 2, '1.1.2', 'Cronograma de hitos y presupuesto detallado', '', 1, 2);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (5, 1, 2, '1.1.3', 'Plan de gestión de riesgos y calidad', '', 2, 2);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (6, 1, 2, '1.1.4', 'Informes de avance y actas de seguimiento', '', 3, 2);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (7, 1, 1, '1.2', 'Análisis y Diseño del Sistema', '', 1, 1);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (8, 1, 7, '1.2.1', 'Documento de requerimientos funcionales y técnicos', '', 0, 2);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (9, 1, 7, '1.2.2', 'Arquitectura del sistema y flujo transaccional', '', 1, 2);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (10, 1, 7, '1.2.3', 'Modelo de datos y diseño del esquema relacional', '', 2, 2);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (11, 1, 7, '1.2.4', 'Prototipos de interfaces de usuario (Dashboard administrativo)', '', 3, 2);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (12, 1, 1, '1.3', 'Dispositivo Validador a Bordo (Hardware IoT)', '', 2, 1);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (13, 1, 12, '1.3.1', 'Módulo lector de proximidad RFID y escáner de códigos QR', '', 0, 2);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (14, 1, 12, '1.3.2', 'Microcontrolador y módulo de comunicación (GSM/4G y GPS)', '', 1, 2);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (15, 1, 12, '1.3.3', 'Carcasa antivandálica y estructura de anclaje para furgón/cabina', '', 2, 2);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (16, 1, 12, '1.3.4', 'Sistema de alimentación regulada (convertidor 12V/24V a 5V)', '', 3, 2);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (17, 1, 1, '1.4', 'Desarrollo del Ecosistema de Software', '', 3, 1);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (18, 1, 17, '1.4.1', 'Firmware del dispositivo validador con almacenamiento offline-first', '', 0, 2);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (19, 1, 17, '1.4.2', 'API Backend y motor transaccional de procesamiento de cobros', '', 1, 2);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (20, 1, 17, '1.4.3', 'Base de datos centralizada con registros de auditoría contable', '', 2, 2);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (21, 1, 17, '1.4.4', 'Portal web administrativo para cooperativas y propietarios de buses', '', 3, 2);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (22, 1, 17, '1.4.5', 'Módulo de emisión, registro de UID y control de saldos', '', 4, 2);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (23, 1, 1, '1.5', 'Pruebas e Integración', '', 4, 1);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (24, 1, 23, '1.5.1', 'Informe de pruebas de lectura RFID/QR y tiempo de respuesta', '', 0, 2);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (25, 1, 23, '1.5.2', 'Informe de pruebas de concurrencia y estrés transaccional', '', 1, 2);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (26, 1, 23, '1.5.3', 'Informe de pruebas de sincronización de datos', '', 2, 2);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (27, 1, 23, '1.5.4', 'Informe de auditoría y seguridad de datos', '', 3, 2);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (28, 1, 1, '1.6', 'Implementación y Validación Piloto', '', 5, 1);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (29, 1, 28, '1.6.1', 'Lote de tarjetas RFID configuradas para la fase de pruebas', '', 0, 2);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (30, 1, 28, '1.6.2', 'Unidad de transporte piloto instalada y conectada', '', 1, 2);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (31, 1, 28, '1.6.3', 'Manuales de operación del validador y guías para conductores', '', 2, 2);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (32, 1, 28, '1.6.4', 'Informe de evaluación operativa en ruta y conciliación financiera', '', 3, 2);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (33, 1, 3, '1.1.1.1', 'Recopilar requerimientos de los patrocinadores y justificación del negocio', '', 0, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (34, 1, 3, '1.1.1.2', 'Redactar acta de constitución y formalizar firma del comité', '', 1, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (35, 1, 4, '1.1.2.1', 'Definir la estructura de desglose de trabajo (EDT) y diccionario', '', 0, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (36, 1, 4, '1.1.2.2', 'Estimar duraciones PERT y consolidar presupuesto base', '', 1, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (37, 1, 5, '1.1.3.1', 'Identificar matriz de riesgos operacionales y técnicos', '', 0, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (38, 1, 5, '1.1.3.2', 'Diseñar métricas de control de calidad y planes de mitigación', '', 1, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (39, 1, 6, '1.1.4.1', 'Establecer plantilla de control de valor ganado (EVM) e indicadores', '', 0, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (40, 1, 6, '1.1.4.2', 'Coordinar reuniones semanales de seguimiento y actas de control', '', 1, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (41, 1, 8, '1.2.1.1', 'Levantar casos de uso de cobro a bordo y recarga de saldos', '', 0, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (42, 1, 8, '1.2.1.2', 'Especificar requerimientos no funcionales de seguridad y latencia', '', 1, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (43, 1, 9, '1.2.2.1', 'Diagramar arquitectura de microservicios y protocolos MQTT/HTTP', '', 0, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (44, 1, 9, '1.2.2.2', 'Diseñar flujo de validación offline-first y cola de sincronización', '', 1, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (45, 1, 10, '1.2.3.1', 'Diseñar diagrama entidad-relación y tablas de transacciones', '', 0, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (46, 1, 10, '1.2.3.2', 'Definir estrategia de indexación, particionamiento y auditoría', '', 1, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (47, 1, 11, '1.2.4.1', 'Diseñar wireframes de alta fidelidad en Figma para panel de control', '', 0, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (48, 1, 11, '1.2.4.2', 'Validar flujo de navegación con gerentes de cooperativas', '', 1, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (49, 1, 13, '1.3.1.1', 'Seleccionar e integrar módulo lector RFID RC522/PN532', '', 0, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (50, 1, 13, '1.3.1.2', 'Calibrar antena de radiofrecuencia y módulo óptico de códigos QR', '', 1, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (51, 1, 14, '1.3.2.1', 'Ensamblar placa base con procesador ESP32-S3 y módem 4G LTE', '', 0, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (52, 1, 14, '1.3.2.2', 'Conectar antena GPS activa y depurar precisión de telemetría', '', 1, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (53, 1, 15, '1.3.3.1', 'Modelar en CAD la envolvente IP54 y soporte mecánico articulado', '', 0, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (54, 1, 15, '1.3.3.2', 'Fabricar prototipos en corte láser e impresión 3D reforzada', '', 1, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (55, 1, 16, '1.3.4.1', 'Diseñar circuito reductor Buck step-down con protección automotriz', '', 0, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (56, 1, 16, '1.3.4.2', 'Soldar y verificar etapas de filtrado y fusible térmico', '', 1, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (57, 1, 18, '1.4.1.1', 'Programar lógica de lectura en C++/FreeRTOS y validación en Flash', '', 0, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (58, 1, 18, '1.4.1.2', 'Implementar rutina de cifrado AES-256 y cola de transacciones', '', 1, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (59, 1, 19, '1.4.2.1', 'Desarrollar endpoints RESTful y WebSocket de sincronización', '', 0, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (60, 1, 19, '1.4.2.2', 'Programar motor de validación de saldos y prevención de doble gasto', '', 1, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (61, 1, 20, '1.4.3.1', 'Desplegar clúster de base de datos con réplicas de lectura', '', 0, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (62, 1, 20, '1.4.3.2', 'Configurar triggers de auditoría inmutable para débitos y créditos', '', 1, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (63, 1, 21, '1.4.4.1', 'Desarrollar módulo de liquidación diaria por unidad de transporte', '', 0, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (64, 1, 21, '1.4.4.2', 'Construir reportes estadísticos de afluencia y exportación contable', '', 1, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (65, 1, 22, '1.4.5.1', 'Crear interfaz para empadronamiento de tarjetas y vinculación', '', 0, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (66, 1, 22, '1.4.5.2', 'Desarrollar módulo de recargas en puntos de venta y conciliación', '', 1, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (67, 1, 24, '1.5.1.1', 'Ejecutar 500 ciclos de lectura con tarjetas físicas a diferentes distancias', '', 0, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (68, 1, 24, '1.5.1.2', 'Medir latencia de confirmación sonora y visual en el validador', '', 1, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (69, 1, 25, '1.5.2.1', 'Simular carga con JMeter de 1,000 transacciones simultáneas', '', 0, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (70, 1, 25, '1.5.2.2', 'Evaluar estabilidad de la cola de sincronización ante pérdida de red 4G', '', 1, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (71, 1, 26, '1.5.3.1', 'Validar reconciliación de cobros offline al reconectar a red Wi-Fi/4G', '', 0, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (72, 1, 26, '1.5.3.2', 'Verificar consistencia de marcas temporales y coordenadas GPS', '', 1, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (73, 1, 27, '1.5.4.1', 'Realizar escaneo de vulnerabilidades en API y base de datos', '', 0, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (74, 1, 27, '1.5.4.2', 'Verificar integridad criptográfica de transacciones y llaves de acceso', '', 1, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (75, 1, 29, '1.6.1.1', 'Inicializar y grabar claves del sector seguro en 100 tarjetas Mifare', '', 0, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (76, 1, 29, '1.6.1.2', 'Rotular e inventariar credenciales para usuarios del plan piloto', '', 1, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (77, 1, 30, '1.6.2.1', 'Montar validador físico en barra pasamanos del bus seleccionado', '', 0, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (78, 1, 30, '1.6.2.2', 'Conectar a batería vehicular y calibrar encendido por ignición', '', 1, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (79, 1, 31, '1.6.3.1', 'Redactar guía rápida plastificada de encendido y alertas', '', 0, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (80, 1, 31, '1.6.3.2', 'Impartir sesión presencial de inducción técnica a conductores', '', 1, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (81, 1, 32, '1.6.4.1', 'Monitorear recaudación en vivo durante 3 días consecutivos de ruta', '', 0, 3);
INSERT INTO nodo_edt (id, proyecto_id, padre_id, codigo, nombre, descripcion, orden, nivel) VALUES (82, 1, 32, '1.6.4.2', 'Comparar corte de caja físico vs balance reportado por el sistema', '', 1, 3);

-- 3. Actividades PERT (Duraciones To, Tm, Tp, Te, Varianza y Responsable)
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (1, 33, 'Recopilar requerimientos de los patrocinadores y justificación del negocio', 1, 2, 3, 2, 0.11, 'Diego');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (2, 34, 'Redactar acta de constitución y formalizar firma del comité', 1, 2, 3, 2, 0.11, 'Diego');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (3, 35, 'Definir la estructura de desglose de trabajo (EDT) y diccionario', 1, 2, 3, 2, 0.11, 'Paredes');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (4, 36, 'Estimar duraciones PERT y consolidar presupuesto base', 2, 3, 4, 3, 0.11, 'Paredes');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (5, 37, 'Identificar matriz de riesgos operacionales y técnicos', 1, 2, 3, 2, 0.11, 'Paredes');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (6, 38, 'Diseñar métricas de control de calidad y planes de mitigación', 1, 2, 3, 2, 0.11, 'Paredes');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (7, 39, 'Establecer plantilla de control de valor ganado (EVM) e indicadores', 1, 2, 3, 2, 0.11, 'Paredes');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (8, 40, 'Coordinar reuniones semanales de seguimiento y actas de control', 2, 3, 4, 3, 0.11, 'Diego');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (9, 41, 'Levantar casos de uso de cobro a bordo y recarga de saldos', 2, 3, 4, 3, 0.11, 'Paredes');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (10, 42, 'Especificar requerimientos no funcionales de seguridad y latencia', 2, 3, 4, 3, 0.11, 'Falcon');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (11, 43, 'Diagramar arquitectura de microservicios y protocolos MQTT/HTTP', 2, 3, 4, 3, 0.11, 'Falcon');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (12, 44, 'Diseñar flujo de validación offline-first y cola de sincronización', 2, 3, 4, 3, 0.11, 'Falcon');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (13, 45, 'Diseñar diagrama entidad-relación y tablas de transacciones', 1, 2, 3, 2, 0.11, 'Salazar');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (14, 46, 'Definir estrategia de indexación, particionamiento y auditoría', 1, 2, 3, 2, 0.11, 'Salazar');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (15, 47, 'Diseñar wireframes de alta fidelidad en Figma para panel de control', 2, 3, 4, 3, 0.11, 'Falcon');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (16, 48, 'Validar flujo de navegación con gerentes de cooperativas', 1, 2, 3, 2, 0.11, 'Falcon');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (17, 49, 'Seleccionar e integrar módulo lector RFID RC522/PN532', 2, 3, 4, 3, 0.11, 'Enrique');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (18, 50, 'Calibrar antena de radiofrecuencia y módulo óptico de códigos QR', 2, 3, 4, 3, 0.11, 'Enrique');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (19, 51, 'Ensamblar placa base con procesador ESP32-S3 y módem 4G LTE', 3, 4, 5, 4, 0.11, 'Enrique');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (20, 52, 'Conectar antena GPS activa y depurar precisión de telemetría', 2, 3, 4, 3, 0.11, 'Enrique');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (21, 53, 'Modelar en CAD la envolvente IP54 y soporte mecánico articulado', 2, 3, 4, 3, 0.11, 'Enrique');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (22, 54, 'Fabricar prototipos en corte láser e impresión 3D reforzada', 2, 3, 4, 3, 0.11, 'Enrique');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (23, 55, 'Diseñar circuito reductor Buck step-down con protección automotriz', 1, 2, 3, 2, 0.11, 'Enrique');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (24, 56, 'Soldar y verificar etapas de filtrado y fusible térmico', 1, 2, 3, 2, 0.11, 'Enrique');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (25, 57, 'Programar lógica de lectura en C++/FreeRTOS y validación en Flash', 4, 5, 6, 5, 0.11, 'Enrique');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (26, 58, 'Implementar rutina de cifrado AES-256 y cola de transacciones', 3, 4, 5, 4, 0.11, 'Enrique');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (27, 59, 'Desarrollar endpoints RESTful y WebSocket de sincronización', 4, 6, 8, 6, 0.44, 'Falcon');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (28, 60, 'Programar motor de validación de saldos y prevención de doble gasto', 3, 5, 7, 5, 0.44, 'Falcon');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (29, 61, 'Desplegar clúster de base de datos con réplicas de lectura', 2, 3, 4, 3, 0.11, 'Salazar');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (30, 62, 'Configurar triggers de auditoría inmutable para débitos y créditos', 1, 2, 3, 2, 0.11, 'Salazar');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (31, 63, 'Desarrollar módulo de liquidación diaria por unidad de transporte', 3, 4, 5, 4, 0.11, 'Falcon');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (32, 64, 'Construir reportes estadísticos de afluencia y exportación contable', 2, 4, 6, 4, 0.44, 'Falcon');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (33, 65, 'Crear interfaz para empadronamiento de tarjetas y vinculación', 2, 3, 4, 3, 0.11, 'Salazar');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (34, 66, 'Desarrollar módulo de recargas en puntos de venta y conciliación', 2, 4, 6, 4, 0.44, 'Salazar');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (35, 67, 'Ejecutar 500 ciclos de lectura con tarjetas físicas a diferentes distancias', 2, 3, 4, 3, 0.11, 'Enrique');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (36, 68, 'Medir latencia de confirmación sonora y visual en el validador', 1, 2, 3, 2, 0.11, 'Enrique');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (37, 69, 'Simular carga con JMeter de 1,000 transacciones simultáneas', 2, 3, 4, 3, 0.11, 'Falcon');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (38, 70, 'Evaluar estabilidad de la cola de sincronización ante pérdida de red 4G', 2, 3, 4, 3, 0.11, 'Falcon');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (39, 71, 'Validar reconciliación de cobros offline al reconectar a red Wi-Fi/4G', 2, 3, 4, 3, 0.11, 'Falcon');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (40, 72, 'Verificar consistencia de marcas temporales y coordenadas GPS', 1, 2, 3, 2, 0.11, 'Falcon');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (41, 73, 'Realizar escaneo de vulnerabilidades en API y base de datos', 2, 3, 4, 3, 0.11, 'Salazar');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (42, 74, 'Verificar integridad criptográfica de transacciones y llaves de acceso', 1, 2, 3, 2, 0.11, 'Salazar');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (43, 75, 'Inicializar y grabar claves del sector seguro en 100 tarjetas Mifare', 1, 2, 3, 2, 0.11, 'Enrique');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (44, 76, 'Rotular e inventariar credenciales para usuarios del plan piloto', 1, 1, 1, 1, 0, 'Enrique');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (45, 77, 'Montar validador físico en barra pasamanos del bus seleccionado', 1, 2, 3, 2, 0.11, 'Enrique');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (46, 78, 'Conectar a batería vehicular y calibrar encendido por ignición', 1, 2, 3, 2, 0.11, 'Enrique');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (47, 79, 'Redactar guía rápida plastificada de encendido y alertas', 1, 2, 3, 2, 0.11, 'Paredes');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (48, 80, 'Impartir sesión presencial de inducción técnica a conductores', 1, 2, 3, 2, 0.11, 'Paredes');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (49, 81, 'Monitorear recaudación en vivo durante 3 días consecutivos de ruta', 3, 4, 5, 4, 0.11, 'Diego');
INSERT INTO actividad (id, nodo_edt_id, nombre, duracion_optimista, duracion_probable, duracion_pesimista, duracion_esperada, varianza, responsable) VALUES (50, 82, 'Comparar corte de caja físico vs balance reportado por el sistema', 2, 3, 4, 3, 0.11, 'Diego');

-- 4. Dependencias de la Red PERT (Predecesoras y Sucesoras)
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (1, 1, 2, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (2, 3, 4, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (3, 5, 6, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (4, 7, 8, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (5, 9, 10, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (6, 11, 12, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (7, 13, 14, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (8, 15, 16, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (9, 17, 18, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (10, 19, 20, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (11, 21, 22, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (12, 23, 24, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (13, 25, 26, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (14, 27, 28, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (15, 29, 30, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (16, 31, 32, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (17, 33, 34, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (18, 35, 36, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (19, 37, 38, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (20, 39, 40, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (21, 41, 42, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (22, 43, 44, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (23, 45, 46, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (24, 47, 48, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (25, 49, 50, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (26, 2, 3, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (27, 2, 5, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (28, 6, 7, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (29, 4, 9, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (30, 10, 11, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (31, 12, 13, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (32, 10, 15, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (33, 12, 17, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (34, 12, 19, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (35, 18, 21, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (36, 20, 23, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (37, 18, 25, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (38, 20, 25, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (39, 14, 27, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (40, 14, 29, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (41, 16, 31, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (42, 28, 31, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (43, 28, 33, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (44, 30, 33, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (45, 26, 35, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (46, 22, 35, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (47, 24, 35, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (48, 28, 37, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (49, 34, 37, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (50, 26, 39, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (51, 28, 39, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (52, 30, 41, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (53, 38, 41, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (54, 34, 43, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (55, 36, 45, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (56, 40, 45, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (57, 32, 47, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (58, 44, 49, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (59, 46, 49, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (60, 48, 49, 'FS', 0);
INSERT INTO dependencia (id, predecesora_id, sucesora_id, tipo, desfase_dias) VALUES (61, 42, 49, 'FS', 0);

COMMIT;
